### ISSUE TITLE
Check Complete Source Code for TE 4.0.5

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-offline#3]
Under Catalina base/lib
- [x] [asm-3.1.jar](https://github.com/opengeospatial/teamengine-offline/tree/master/src/teamengine-4.0.5-dependencies/asm_asm_3.1)
- [x] [derby-10.10.1.1.jar](https://github.com/opengeospatial/teamengine-offline/tree/master/src/teamengine-4.0.5-dependencies/org_apache_derby_derby_10.10.1.1)
- [ ] jersey-client-1.17.1.jar - missing?
  - Appears under test suites dependencies [1.18.1](https://github.com/opengeospatial/teamengine-offline/tree/master/src/test-suite-dependencies/jersey-client-1.18.1-sources)
- [x] [jersey-core-1.17.1.jar](https://github.com/opengeospatial/teamengine-offline/tree/master/src/teamengine-4.0.5-dependencies/com_sun_jersey_jersey-core_1.17.1)
- [x] [jersey-server-1.17.1.jar](https://github.com/opengeospatial/teamengine-offline/tree/master/src/teamengine-4.0.5-dependencies/com_sun_jersey_jersey-server_1.17.1)
- [x] [jersey-servlet-1.17.1.jar](https://github.com/opengeospatial/teamengine-offline/tree/master/src/teamengine-4.0.5-dependencies/com_sun_jersey_jersey-servlet_1.17.1)
- [x] jsr311-api-1.1.1.jar - missing?
  - Appears under test suite dependencies [275-0.9.3](https://github.com/opengeospatial/teamengine-offline/tree/master/src/test-suite-dependencies/jsr-275-0.9.3-sources)
- [x] teamengine-realm-4.0.5.jar

**Comment by rjmartell** [comment]
The jersey-client component is required by some of the test suites, not teamengine itself so that's why it's listed as a test suite dependency. It shouldn't show up in a teamengine build.

I added the missing source for jsr311-api-1.1.1.jar.

The teamengine-realm component is one of the teamengine modules.
